### ISSUE TITLE
Tail wheel lock

### ISSUE THREAD

**Issue by SP-K79** [FGMEMBERS/pa20#1]
Thank you Israel for including this in FGMEMBERS.

Before I added this:

```
<gear x="-5" y="0" z="-0.25" compression="0.16"> <!-- tailwheel  -->
  <control-input axis="/controls/flight/rudder" control="STEER"
                 src0="-1.0" src1="1.0"
                 dst0="0.3" dst1="-0.3"/>
</gear>
```

the plane had no ground steering what so ever.

As all tail draggers are, it too is a handful on takeoff.  The issue here is that this plane has no tail lock at all.  This makes normal takeoff extremely hard.

I did this:

```
<gear x="-5" y="0" z="-0.25" compression="0.16"> <!-- tailwheel  -->
  <control-input axis="/controls/flight/rudder" control="STEER"
                 src0="-1.0" src1="1.0"
                 dst0="0.3" dst1="-0.3"/>
  <control-input axis="/controls/gear/tailwheel-lock" src0="0" src1="1"
                 dst0="1" dst1="0" control="STEER"/>
</gear>
```

and now under /controls/gear/tailwheel-lock at least it changes from 'true' to 'false' with the effect that when it is at 'false', all it does is turn left in a circle with no response to the controls input.

The steering without the lock on the ground is fine, it's just the lock that is needed.

Your help will be much appreciated, I'm sure.

Thank you in advance,

Peter

**Comment by FGDATA** [comment]
---

> Thank you Israel for including this in FGMEMBERS.

Thank you for pointing it to us :package: 
Best,
@IAHM-COL

**Comment by SP-K79** [comment]
Finally fixed.

```
<gear x="-5" y="0" z="-0.25" compression="0.16"> <!-- tailwheel  -->
  <control-input axis="/controls/gear/tailwheel-lock" control="CASTERING"
                 src0="0" src1="1"
                 dst0="1" dst1="0"/>
</gear>

<!-- tail wheel -->
<gear x="-5" y="0" z="-0.25" compression="0.16" spring="0.8">
  <control-input axis="/controls/flight/rudder" control="STEER"
                 src0="-1.0" src1="1.0"
                 dst0="0.3" dst1="-0.3"/>
</gear>
```

**Comment by SP-K79** [comment]
The two xml files with fixed issue available in my repo.

**Comment by FGDATA** [comment]
Great work SP-K79
https://github.com/FGMEMBERS/pa20/commit/64d5e3bd68944038dfdfb50e9cc3b3018cca29da

Best, IH-COL
